# Generated by Django 2.1.3 on 2018-11-06 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileProcess',
        ),
    ]
