# Generated by Django 2.1.3 on 2018-11-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fileprocess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileprocess',
            old_name='file_path',
            new_name='img_name',
        ),
        migrations.RenameField(
            model_name='fileprocess',
            old_name='img_path',
            new_name='src_file_path',
        ),
    ]
